version: "3.8"

services:
  dynamodb-local:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb
    user: root
    volumes:
      - dynamodb_data:/home/dynamodb
    ports:
      - "8000:8000"

volumes:
  dynamodb_data: